---
- name: Setup Node
  hosts: all
  become: no
  vars:
    NODE_VERS: 18.4.0
  become_flags: -i # Execute config files such as .profile (Ansible uses non-interactive login shells)
  tasks:
    - name: Install nvm
      shell: >
        curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.38.0/install.sh | bash
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/nvm.sh"

    - name: Setup .profile
      lineinfile:
        path: ~/.profile
        line: source ~/.nvm/nvm.sh # This will make sure Node is on the user's PATH
        create: yes

    - name: Install node
      shell: |
        source ~/.nvm/nvm.sh && nvm install {{item}}
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/versions/node/v{{item}}"
      loop:
        - "{{ NODE_VERS }}"

- name: Install node for root
  hosts: all
  become: yes
  tasks:
    - name: Update system
      apt:
        upgrade: dist
        update_cache: yes

    - name: install default nodejs
      apt:
        name: nodejs
        state: present

    - name: install npm
      apt:
        name: npm
        state: present

    - name: install pm2 gloablly
      npm:
        name: pm2
        global: yes
        state: present
          
